# **PANDAS**

In [ ]:
"""
df.shape          # how big is it?
df.info()         # dtypes + null counts
df.head()         # first look
df.describe()     # statistical summary
df.isnull().sum() # null overview
df['col'].value_counts()  # distribution of key columns

"""

In [ ]:
"""

df['col']                          # single column
df[['col1', 'col2']]               # multiple columns
df.iloc[0:5, 0:3]                  # by position
df.loc[0:4, ['col1', 'col2']]      # by label
df[df['col'] == 'value']           # filter rows
df[(condition1) & (condition2)]    # multiple conditions
df['col'].isin(['a', 'b'])         # filter by list
df.query("col == 'value'")         # SQL style
df['col'].str.contains('text')     # text filter

"""

In [ ]:
"""
# 1. finding missing values
# 2. Droping nulls
# 3. Filling nulls
# 4. renaming columns
# 5. dropping columns and rows
# 6. changing data types
# 7. converting date columns into date type
# 8. removing Duplicates
# 9. String cleaning

df.isnull().sum()               # find nulls
df.dropna(subset=['col'])       # drop null rows
df['col'].fillna('Unknown')     # fill nulls
df.rename(columns={})           # rename columns
df.drop(columns=[])             # drop columns
df.astype()                     # fix dtypes
pd.to_datetime(df['col'])       # parse dates
df.drop_duplicates()            # remove duplicates
df['col'].str.strip().lower()   # clean strings

In [ ]:
"""
df.assign(col = ...)                    # add new column safely
df['col'].apply(func)                   # custom function per row
df['col'].map({old: new})              # replace values via dict
df.sort_values('col', ascending=False) # sort
pd.cut(df['col'], bins, labels)        # custom bins
pd.qcut(df['col'], q=4)               # equal sized bins
np.where(condition, true_val, false_val) # fast if-else

"""

In [ ]:
"""
df.groupby('col')['col2'].count()          # basic groupby
df.groupby('col').agg(name=('col','func')) # named aggregation
df.groupby(['col1','col2'])['col3'].count()# multiple columns
df.groupby('col')['col2'].transform('count') # keep original shape
pd.pivot_table(df, values, index, columns) # 2D summary
pd.crosstab(df['col1'], df['col2'])        # frequency table
.reset_index()                             # flatten after groupby

"""

In [ ]:
"""
df1.merge(df2, on='key', how='left')           # left join
df1.merge(df2, on='key', how='inner')          # inner join
df1.merge(df2, on='key', how='outer')          # outer join
df1.merge(df2, left_on='a', right_on='b')      # different key names
df1.merge(df2, on=['key1','key2'])             # multiple keys
pd.concat([df1, df2])                          # stack vertically
pd.concat([df1, df2], axis=1)                  # stack horizontally
df1.merge(df2, indicator=True)                 # validate merge
"""

In [ ]:
"""
pd.to_datetime(df['col'])          # convert to datetime
df['col'].dt.year / month / day    # extract parts
df.set_index('date_col')           # set datetime index
df_ts.resample('M')['col'].count() # group by time frequency
df_ts.rolling(window=3).mean()     # rolling average
df['col'].shift(1)                 # lag by 1 period
df['col'].pct_change()             # % change from previous row
df['col'].diff()                   # absolute change from previous row

"""

In [ ]:
"""
1. Vectorize — never loop with iterrows()
2. Use .assign() — never modify df directly in notebooks
3. Use category dtype — for low cardinality text columns
4. Select columns early — don't carry unnecessary columns
5. Use .copy() — when subsetting df for separate use
6. reset_index() — always after groupby
7. parse_dates at load time — not after
8. Method chain — zero intermediate variables
9. Sanity check — verify shape/counts after every major step

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/netflix_titles.csv')#nrows=100,usecols=[''], parse_dates=['column with date-here[date_added]'] and many more)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df['title']
type(df['title'])

pandas.core.series.Series

In [ ]:
type(df)
df.shape

(8807, 12)

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df.size # rows x colm

105684

In [ ]:
df.index

RangeIndex(start=0, stop=8807, step=1)

In [ ]:
# to set index any column
(
    df
    .set_index("title")
    .head(2)
)

,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
title,,,,,,,,,,,
Dick Johnson Is Dead,s1,Movie,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
Blood & Water,s2,TV Show,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df.describe() # by default - only numeric columns
df.describe(include='object') # only for non numeric columns
df.describe(include='all') # include both

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [ ]:
(
    df.isnull()
    .sum()/len(df)*100
)

show_id          0.00
type             0.00
title            0.00
director        29.91
cast             9.37
country          9.44
date_added       0.11
release_year     0.00
rating           0.05
duration         0.03
listed_in        0.00
description      0.00
dtype: float64

In [ ]:
df.nunique() # each columns unique count
df['release_year'].unique() # shows unique values
df['type'].value_counts() #shows both values and their count like group by

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [ ]:
(
    df['rating']
    .value_counts(normalize=True)  # shows % instead of count
    .mul(100)
    .round(2)
)

rating
TV-MA       36.43
TV-14       24.54
TV-PG        9.80
R            9.08
PG-13        5.57
TV-Y7        3.79
TV-Y         3.49
PG           3.26
TV-G         2.50
NR           0.91
G            0.47
TV-Y7-FV     0.07
NC-17        0.03
UR           0.03
74 min       0.01
84 min       0.01
66 min       0.01
Name: proportion, dtype: float64

In [ ]:
(
    df[['title','type','release_year']]
    .head()
)

                   title     type  release_year
0   Dick Johnson Is Dead    Movie          2020
1          Blood & Water  TV Show          2021
2              Ganglands  TV Show          2021
3  Jailbirds New Orleans  TV Show          2021
4           Kota Factory  TV Show          2021

In [ ]:
#.iloc[] — by position (like a list)
df.iloc[1]
df.iloc[-1]

df.iloc[0:5] # index wise total 5 #last one is excluded
df.iloc[0:5, 0:5] # rows, columns  #last one is excluded

,show_id,type,title,director,cast
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K..."

In [ ]:
# single row by index label
df.loc[0]        # row where index = 0

# specific rows and columns by name
df.loc[0:4, ['title', 'type', 'rating']] # we need to mentioned columns and also last one in inclusive

# all rows, specific columns
df.loc[:, ['title', 'director']]

                      title         director
0      Dick Johnson Is Dead  Kirsten Johnson
1             Blood & Water              NaN
2                 Ganglands  Julien Leclercq
3     Jailbirds New Orleans              NaN
4              Kota Factory              NaN
...                     ...              ...
8802                 Zodiac    David Fincher
8803            Zombie Dumb              NaN
8804             Zombieland  Ruben Fleischer
8805                   Zoom     Peter Hewitt
8806                 Zubaan      Mozez Singh

[8807 rows x 2 columns]

In [ ]:
# it shows all those 3 columns where type is movie
(
    df[df['type'] == 'Movie']
    [['title', 'release_year', 'rating']]
    .head()
)

                               title  release_year rating
0               Dick Johnson Is Dead          2020  PG-13
6   My Little Pony: A New Generation          2021     PG
7                            Sankofa          1993  TV-MA
9                       The Starling          2021  PG-13
12                      Je Suis Karl          2021  TV-MA

In [ ]:
df[(df['type']=='Movie') & (df['release_year'] > 2015)] # both

df[(df['type']=='Movie') | (df['release_year'] > 2015)] #atleast one

df[~(df['type']=='Movie')] # except this condition

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [ ]:
# instead of multiple OR conditions
# .isin() is just a shortcut to replace multiple OR conditions on the SAME column with EXACT values — nothing more, nothing less.

# these are exactly the same
df[(df['rating'] == 'PG') | (df['rating'] == 'PG-13') | (df['rating'] == 'G')]

# vs clean version
df[df['rating'].isin(['PG', 'PG-13', 'G'])]

                                        title rating   type
0                        Dick Johnson Is Dead  PG-13  Movie
6            My Little Pony: A New Generation     PG  Movie
9                                The Starling  PG-13  Movie
27                                  Grown Ups  PG-13  Movie
28                                 Dark Skies  PG-13  Movie
29                                   Paranoia  PG-13  Movie
38                        Birth of the Dragon  PG-13  Movie
41                                       Jaws     PG  Movie
42                                     Jaws 2     PG  Movie
43                                     Jaws 3     PG  Movie
44                          Jaws: The Revenge  PG-13  Movie
45                     My Heroes Were Cowboys     PG  Movie
88   Blood Brothers: Malcolm X & Muhammad Ali  PG-13  Movie
94                                  Show Dogs     PG  Movie
107                          A Champion Heart      G  Movie

In [ ]:
(
    df.query("type == 'Movie' and release_year > 2015 and rating == 'PG-13'")
    [['title', 'release_year', 'country']]
    .head(10)
)

,title,release_year,country
0,Dick Johnson Is Dead,2020,United States
9,The Starling,2021,United States
38,Birth of the Dragon,2017,"China, Canada, United States"
88,Blood Brothers: Malcolm X & Muhammad Ali,2021,NaN
112,Worth,2021,NaN
117,Final Account,2021,"United Kingdom, United States"
128,Agatha Christie's Crooked House,2017,NaN
162,Marshall,2017,"United States, China, Hong Kong"
171,Same Kind of Different as Me,2017,United States
283,Misha and the Wolves,2021,"Belgium, United Kingdom"

In [ ]:
# titles that contain 'Love'
df[df['title'].str.contains('Love', na=False)] # na means null value

# country starts with 'United'
df[df['country'].str.startswith('United', na=False)]

# case insensitive search
df[df['title'].str.contains('love', case=False, na=False)]

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
# drop rows where ANY column has null
df.dropna()

# drop rows where SPECIFIC column has null
df.dropna(subset=['rating'])

# drop rows where ALL columns are null
df.dropna(how='all')

# drop columns that have nulls
df.dropna(axis=1)

In [ ]:
# ✅ clean chaining approach
(
    df
    .dropna(subset=['director'])
    [['title', 'director', 'country']]
    .head()
)

In [ ]:
# fill with a static value
df['rating'].fillna('Not Rated')

# text columns → fill with 'Unknown' or most frequent value
df['country'].fillna('Unknown')
df['rating'].fillna(df['rating'].mode()[0])  # most frequent rating

# fill with mean/median — for numeric columns
df['release_year'].fillna(df['release_year'].mean())

# numeric columns → fill with median (more robust than mean)
df['release_year'].fillna(df['release_year'].median())

# fill with forward fill — use previous row's value
df['date_added'].fillna(method='ffill')

# fill with backward fill — use next row's value
df['date_added'].fillna(method='bfill')

In [ ]:
# rename specific columns
# 💼 Industry Practice — rename while chaining
(
    df.rename(columns={'listed_in': 'genre'
                       'date_added': 'added_date'
                       })
    [['title', 'genre', 'type']]
    .head()
)

In [ ]:
# make all columns lowercase, replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [ ]:
# drop single column
df.drop(columns=['show_id'])

# drop multiple columns
df.drop(columns=['show_id', 'description'])

# drop specific rows by index
df.drop(index=[0, 1, 2])

# 💼 Industry Practice — chain it
(
    df.drop(columns=['show_id', 'description'])
    .head()
)

In [ ]:
# check current dtypes
df.dtypes

# convert release_year from int to string
df['release_year'].astype(str)

# convert a column to category — saves memory on repetitive text
df['type'].astype('category')
df['rating'].astype('category')

In [ ]:
df['country'].memory_usage()

70588

In [ ]:
df['country'].astype('category').memory_usage()

40282

In [ ]:
# check duplicates
df.duplicated().sum()

# check duplicates on specific column
df.duplicated(subset=['title']).sum()

# view duplicate rows
df[df.duplicated(subset=['title'])]

# drop duplicates
df.drop_duplicates()

# drop duplicates on specific column, keep last occurrence
df.drop_duplicates(subset=['title'], keep='last')

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [ ]:
# convert date_added from string to datetime
df['date_added'] = pd.to_datetime(df['date_added'])

# now you can extract parts
df['date_added'].dt.year
df['date_added'].dt.month
df['date_added'].dt.day_name()   # Monday, Tuesday...

# 💼 Industry Practice — create new columns from dates
(
    df.assign(
        year_added = df['date_added'].dt.year,
        month_added = df['date_added'].dt.month
    )
    [['title', 'date_added', 'year_added', 'month_added']]
    .head()
)

In [ ]:
# remove leading/trailing spaces
df['title'].str.strip()

# convert to lowercase
df['title'].str.lower()

# replace within string
df['duration'].str.replace(' min', '').str.replace(' Season', 'S')

# split a column — duration has '90 min' or '2 Seasons'
df['duration'].str.split(' ', expand=True)
#    0       1
# 0  90     min
# 1  2   Seasons

In [ ]:
df['type'].value_counts()

(
    df
    .assign(is_tv = df['type']=='TV Show')
    .head(2)
)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,is_tv
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",False
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",True

In [ ]:
df['release_year'].value_counts()

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
        ...
1961       1
1925       1
1959       1
1966       1
1947       1
Name: count, Length: 74, dtype: int64

In [ ]:
(
    df
    .assign(era = df['release_year'].apply(
        lambda x: 'classic' if x < 2000 else '2000s' if x < 2010 else 'modern'
    ))
    .sample(2)
)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,era
7063,s7064,Movie,Incoming,Eric Zaragosa,"Scott Adkins, Aaron McCusker, Vahldin Prelic, ...","Serbia, United States","October 26, 2018",2019,TV-MA,89 min,"Action & Adventure, Sci-Fi & Fantasy",When an imprisoned terrorist cell hijacks a hi...,modern
7637,s7638,Movie,Ocean's Eleven,Lewis Milestone,"Frank Sinatra, Dean Martin, Sammy Davis Jr., P...",United States,"November 1, 2019",1960,TV-PG,127 min,"Action & Adventure, Classic Movies, Comedies",Frank Sinatra leads an all-star cast as Danny ...,classic

In [ ]:
(
    df
    .assign(short_form = df['type']
              .map({'Movie':'M','TV Show':'TV'}))
    .head(2)
)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,short_form
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",M
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",TV

In [ ]:
# sort by release year
(
    df.sort_values('release_year')
    [['title', 'release_year']]
    .head()
)

# sort descending
(
    df.sort_values('release_year', ascending=False)
    [['title', 'release_year']]
    .head()
)

# sort by multiple columns
(
    df.sort_values(['type', 'release_year'], ascending=[True, False])
    [['title', 'type', 'release_year']]
    .head(10)
)

In [ ]:
#Use when you want to create categories from numbers with your own defined ranges:
#bin release_year into custom ranges
bins = [1900, 1999, 2009, 2021]
labels = ['Classic', '2000s', '2010s']

(
    df
    .assign(era = pd.cut(df['release_year'], bins=bins, labels=labels))
    .head(10)
)

In [ ]:
# split release_year into 4 equal groups
(
    df
    .assign(year_quartile = pd.qcut(df['release_year'], q=4, labels=['Q1','Q2','Q3','Q4']))
    .head(10)
)

In [ ]:
# keep value where condition is True, replace with other where False
(
    df
    .assign(type_label = df['type'].where(df['type'] == 'Movie', other='Not a Movie'))
    .head()
)

In [ ]:
(
    df
    .assign(
        #1
        era          = pd.cut(df['release_year'], bins=[1900,1999,2009,2021],
                              labels=['Classic','2000s','2010s']),
        #2
        is_movie     = df['type'] == 'Movie',
        #3
        content_type = np.where(df['type'] == 'Movie', 'Film', 'Series')
           )
    .dropna(subset=['country', 'rating'])
    .sort_values('release_year', ascending=False)
    .head(10)
)

In [ ]:
# how many titles per type?
(
    df.groupby('type')['title'].count()
)

type
Movie      6131
TV Show    2676
Name: title, dtype: int64

In [ ]:
# average release year per type
(
    df.groupby('type')['release_year'].mean().round()
)

type
Movie      2013.0
TV Show    2017.0
Name: release_year, dtype: float64

In [ ]:
# multiple stats on one column
(
    df.groupby('type')['release_year'].agg(['mean', 'min', 'max', 'count'])
)

                mean   min   max  count
type
Movie    2013.121514  1942  2021   6131
TV Show  2016.605755  1925  2021   2676

In [ ]:
# different stats on different columns
(
    df.groupby('type').agg(
        total_titles  = ('title', 'count'),
        avg_year      = ('release_year', 'mean'),
        latest        = ('release_year', 'max'),
        oldest        = ('release_year', 'min')
    ).round(2)
)

         total_titles  avg_year  latest  oldest
type
Movie            6131   2013.12    2021    1942
TV Show          2676   2016.61    2021    1925

In [ ]:
# count titles by type AND rating
(
    df.groupby(['type', 'rating'])['title']
    .count()
    .reset_index()
    .rename(columns={'title': 'count'})
    .sort_values('count', ascending=False)
    .head(10)
)

       type rating  count
11    Movie  TV-MA   2062
9     Movie  TV-14   1427
21  TV Show  TV-MA   1145
8     Movie      R    797
19  TV Show  TV-14    733
12    Movie  TV-PG    540
7     Movie  PG-13    490
22  TV Show  TV-PG    323
6     Movie     PG    287
24  TV Show  TV-Y7    195

In [ ]:
# add a column showing total titles per type — next to each row
(
    df.assign(
        total_by_type = df.groupby('type')['title'].transform('count')
    )
    [['title', 'type', 'total_by_type']]
    .head(10)
)

                              title     type  total_by_type
0              Dick Johnson Is Dead    Movie           6131
1                     Blood & Water  TV Show           2676
2                         Ganglands  TV Show           2676
3             Jailbirds New Orleans  TV Show           2676
4                      Kota Factory  TV Show           2676
5                     Midnight Mass  TV Show           2676
6  My Little Pony: A New Generation    Movie           6131
7                           Sankofa    Movie           6131
8     The Great British Baking Show  TV Show           2676
9                      The Starling    Movie           6131

In [ ]:
# count of titles by type (rows) and rating (columns)
(
    pd.pivot_table(
        df,
        values  = 'title',
        index   = 'type',
        columns = 'rating',
        aggfunc = 'count'
    )
    .fillna(0)
    .astype(int)
)

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Movie,1,1,1,41,3,75,287,490,797,1427,126,2062,540,131,139,5,3
TV Show,0,0,0,0,0,5,0,0,2,733,94,1145,323,176,195,1,0

In [ ]:
# frequency of type vs rating
(
    pd.crosstab(df['type'], df['rating'])
)

rating,66 min,74 min,84 min,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,,
Movie,1,1,1,41,3,75,287,490,797,1427,126,2062,540,131,139,5,3
TV Show,0,0,0,0,0,5,0,0,2,733,94,1145,323,176,195,1,0

In [ ]:
# top 10 countries by number of movies on Netflix
(
    df[df['type'] == 'Movie']
    .dropna(subset=['country'])
    .groupby('country')
    .agg(total_movies = ('title', 'count'))
    .reset_index()
    .sort_values('total_movies', ascending=False)
    .head(10)
)

            country  total_movies
525   United States          2058
218           India           893
440  United Kingdom           206
50           Canada           122
384           Spain            97
128           Egypt            92
319         Nigeria            86
238       Indonesia            77
278           Japan            76
428          Turkey            76

In [ ]:
# DataFrame 1 — netflix titles
df_titles = (
    df[['show_id', 'title', 'type', 'release_year']]
    .head(10)
)

# DataFrame 2 — netflix ratings (simulating a separate table)
df_ratings = (
    df[['show_id', 'rating', 'duration']]
    .head(8)                              # intentionally 8 not 10
)                                         # so we can see join differences

In [ ]:
(
    df_titles.merge(df_ratings, on='show_id', how='inner') #outer #left #right
)

In [ ]:
# when you need more than one column to uniquely identify a row
(
    df.merge(df_ratings, on=['show_id', 'type'], how='left')
)

In [ ]:
# split netflix into movies and shows
df_movies   = df[df['type'] == 'Movie'].head(5)
df_tvshows  = df[df['type'] == 'TV Show'].head(5)

# stack them back together vertically
(
    pd.concat([df_movies, df_tvshows])
    .reset_index(drop=True)
)

In [ ]:
# first lets just see the full merge result with indicator
(
    df_titles.merge(df_ratings, on='show_id', how='outer', indicator=True)
)

In [ ]:
show_id   title          type    release_year  rating   duration   _merge
0  s1        Dick Johnson   Movie   2020          PG-13    90 min     both        ← found in both
1  s2        Blood & Water  TV Show 2021          TV-MA    2 Seasons  both        ← found in both
...
8  s9        Jailbirds      TV Show 2019          NaN      NaN        left_only   ← only in df_titles
9  s10       Valeria        TV Show 2020          NaN      NaN        left_only   ← only in df_titles

In [ ]:
# convert date_added to datetime
df['date_added'] = pd.to_datetime(df['date_added'])

df = pd.read_csv('netflix_titles.csv', parse_dates=['date_added'])

In [ ]:
# extract individual parts
df['date_added'].dt.year        # 2021
df['date_added'].dt.month       # 1
df['date_added'].dt.day         # 25
df['date_added'].dt.day_name()  # Monday
df['date_added'].dt.month_name()# January
df['date_added'].dt.quarter     # 1
df['date_added'].dt.weekday     # 0=Monday, 6=Sunday

# 💼 Industry Practice — create multiple date columns at once
(
    df.assign(
        year_added  = df['date_added'].dt.year,
        month_added = df['date_added'].dt.month,
        day_added   = df['date_added'].dt.day_name(),
        quarter     = df['date_added'].dt.quarter
    )
    [['title', 'date_added', 'year_added', 'month_added', 'day_added', 'quarter']]
    .head()
)

In [ ]:
# 💼 Industry Practice — cleaner way using .query()
(
    df.query("date_added >= '2019-01-01' and date_added <= '2020-12-31'")
    [['title', 'date_added']]
    .head()
)

In [ ]:
# how many titles added per year?
(
    df_ts.resample('Y')['title']
    .count()
    .reset_index()
    .rename(columns={'title': 'total_added'})
)

In [ ]:
date_added    total_added
2008-12-31         2
2009-12-31         2
2010-12-31        13
...
2021-12-31       1498

In [ ]:
# how has Netflix content addition grown year over year?
(
    df
    .dropna(subset=['date_added'])
    .assign(date_added = pd.to_datetime(df['date_added']))
    .set_index('date_added')
    .sort_index()
    .resample('Y')['title']
    .count()
    .reset_index()
    .rename(columns={'title': 'total_added', 'date_added': 'year'})
    .assign(
        yoy_change  = lambda x: x['total_added'].diff(),
        yoy_pct     = lambda x: x['total_added'].pct_change().mul(100).round(2)
    )
)

In [ ]:
# 💼 Industry Practice — a full clean pipeline
(
    df
    # 1. fix dtypes first
    .assign(date_added = pd.to_datetime(df['date_added']))
    .astype({'type': 'category', 'rating': 'category'})

    # 2. clean nulls
    .dropna(subset=['country', 'rating'])
    .fillna({'director': 'Unknown', 'cast': 'Unknown'})

    # 3. transform
    .assign(
        era          = pd.cut(df['release_year'],
                              bins=[1900,1999,2009,2021],
                              labels=['Classic','2000s','2010s']),
        year_added   = lambda x: x['date_added'].dt.year,
        content_type = np.where(df['type'] == 'Movie', 'Film', 'Series')
    )

    # 4. filter
    .query("release_year >= 2000")

    # 5. select only needed columns
    [['title', 'content_type', 'era', 'year_added', 'country', 'rating']]
)

In [ ]:
# define steps as functions
def fix_dtypes(df):
    return df.assign(date_added = pd.to_datetime(df['date_added']))

def clean_nulls(df):
    return df.dropna(subset=['country', 'rating'])

def add_features(df):
    return df.assign(
        year_added   = df['date_added'].dt.year,
        content_type = np.where(df['type'] == 'Movie', 'Film', 'Series')
    )

# connect with .pipe() — reads like a story
(
    df
    .pipe(fix_dtypes)
    .pipe(clean_nulls)
    .pipe(add_features)
    .head()
)

In [ ]:
# 1. LOAD
df = pd.read_csv('netflix_titles.csv', parse_dates=['date_added'])

# 2. INSPECT
df.shape
df.info()
df.isnull().sum()
df.describe()

# 3. CLEAN
df = (
    df
    .drop_duplicates()
    .dropna(subset=['country', 'rating'])
    .fillna({'director': 'Unknown', 'cast': 'Unknown'})
    .astype({'type': 'category', 'rating': 'category'})
)

# 4. TRANSFORM
df = (
    df
    .assign(
        year_added   = df['date_added'].dt.year,
        content_type = np.where(df['type'] == 'Movie', 'Film', 'Series'),
        era          = pd.cut(df['release_year'],
                              bins=[1900,1999,2009,2021],
                              labels=['Classic','2000s','2010s'])
    )
)

# 5. ANALYSE
(
    df.groupby(['content_type', 'era'])
    .agg(total = ('title', 'count'))
    .reset_index()
    .sort_values('total', ascending=False)
)