# **PANDAS**

In [ ]:
"""
df.shape          # how big is it?
df.info()         # dtypes + null counts
df.head()         # first look
df.describe()     # statistical summary
df.isnull().sum() # null overview
df['col'].value_counts()  # distribution of key columns

"""

In [ ]:
"""

df['col']                          # single column
df[['col1', 'col2']]               # multiple columns
df.iloc[0:5, 0:3]                  # by position
df.loc[0:4, ['col1', 'col2']]      # by label
df[df['col'] == 'value']           # filter rows
df[(condition1) & (condition2)]    # multiple conditions
df['col'].isin(['a', 'b'])         # filter by list
df.query("col == 'value'")         # SQL style
df['col'].str.contains('text')     # text filter

"""

In [ ]:
"""
# 1. finding missing values
# 2. Droping nulls
# 3. Filling nulls
# 4. renaming columns
# 5. dropping columns and rows
# 6. changing data types
# 7. converting date columns into date type
# 8. removing Duplicates
# 9. String cleaning

df.isnull().sum()               # find nulls
df.dropna(subset=['col'])       # drop null rows
df['col'].fillna('Unknown')     # fill nulls
df.rename(columns={})           # rename columns
df.drop(columns=[])             # drop columns
df.astype()                     # fix dtypes
pd.to_datetime(df['col'])       # parse dates
df.drop_duplicates()            # remove duplicates
df['col'].str.strip().lower()   # clean strings

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/netflix_titles.csv')#nrows=100,usecols=[''], parse_dates=['column with date-here[date_added]'] and many more)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [4]:
df['title']
type(df['title'])

pandas.core.series.Series

In [ ]:
type(df)
df.shape

(8807, 12)

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df.size # rows x colm

105684

In [ ]:
df.index

RangeIndex(start=0, stop=8807, step=1)

In [ ]:
# to set index any column
(
    df
    .set_index("title")
    .head(2)
)

,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
title,,,,,,,,,,,
Dick Johnson Is Dead,s1,Movie,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
Blood & Water,s2,TV Show,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df.describe() # by default - only numeric columns
df.describe(include='object') # only for non numeric columns
df.describe(include='all') # include both

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [ ]:
(
    df.isnull()
    .sum()/len(df)*100
)

show_id          0.00
type             0.00
title            0.00
director        29.91
cast             9.37
country          9.44
date_added       0.11
release_year     0.00
rating           0.05
duration         0.03
listed_in        0.00
description      0.00
dtype: float64

In [5]:
df.nunique() # each columns unique count
df['release_year'].unique() # shows unique values
df['type'].value_counts() #shows both values and their count like group by

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [ ]:
(
    df['rating']
    .value_counts(normalize=True)  # shows % instead of count
    .mul(100)
    .round(2)
)

rating
TV-MA       36.43
TV-14       24.54
TV-PG        9.80
R            9.08
PG-13        5.57
TV-Y7        3.79
TV-Y         3.49
PG           3.26
TV-G         2.50
NR           0.91
G            0.47
TV-Y7-FV     0.07
NC-17        0.03
UR           0.03
74 min       0.01
84 min       0.01
66 min       0.01
Name: proportion, dtype: float64

In [ ]:
(
    df[['title','type','release_year']]
    .head()
)

                   title     type  release_year
0   Dick Johnson Is Dead    Movie          2020
1          Blood & Water  TV Show          2021
2              Ganglands  TV Show          2021
3  Jailbirds New Orleans  TV Show          2021
4           Kota Factory  TV Show          2021

In [ ]:
#.iloc[] — by position (like a list)
df.iloc[1]
df.iloc[-1]

df.iloc[0:5] # index wise total 5 #last one is excluded
df.iloc[0:5, 0:5] # rows, columns  #last one is excluded

,show_id,type,title,director,cast
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K..."

In [ ]:
# single row by index label
df.loc[0]        # row where index = 0

# specific rows and columns by name
df.loc[0:4, ['title', 'type', 'rating']] # we need to mentioned columns and also last one in inclusive

# all rows, specific columns
df.loc[:, ['title', 'director']]

                      title         director
0      Dick Johnson Is Dead  Kirsten Johnson
1             Blood & Water              NaN
2                 Ganglands  Julien Leclercq
3     Jailbirds New Orleans              NaN
4              Kota Factory              NaN
...                     ...              ...
8802                 Zodiac    David Fincher
8803            Zombie Dumb              NaN
8804             Zombieland  Ruben Fleischer
8805                   Zoom     Peter Hewitt
8806                 Zubaan      Mozez Singh

[8807 rows x 2 columns]

In [ ]:
# it shows all those 3 columns where type is movie
(
    df[df['type'] == 'Movie']
    [['title', 'release_year', 'rating']]
    .head()
)

                               title  release_year rating
0               Dick Johnson Is Dead          2020  PG-13
6   My Little Pony: A New Generation          2021     PG
7                            Sankofa          1993  TV-MA
9                       The Starling          2021  PG-13
12                      Je Suis Karl          2021  TV-MA

In [ ]:
df[(df['type']=='Movie') & (df['release_year'] > 2015)] # both

df[(df['type']=='Movie') | (df['release_year'] > 2015)] #atleast one

df[~(df['type']=='Movie')] # except this condition

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [ ]:
# instead of multiple OR conditions
# .isin() is just a shortcut to replace multiple OR conditions on the SAME column with EXACT values — nothing more, nothing less.

# these are exactly the same
df[(df['rating'] == 'PG') | (df['rating'] == 'PG-13') | (df['rating'] == 'G')]

# vs clean version
df[df['rating'].isin(['PG', 'PG-13', 'G'])]

                                        title rating   type
0                        Dick Johnson Is Dead  PG-13  Movie
6            My Little Pony: A New Generation     PG  Movie
9                                The Starling  PG-13  Movie
27                                  Grown Ups  PG-13  Movie
28                                 Dark Skies  PG-13  Movie
29                                   Paranoia  PG-13  Movie
38                        Birth of the Dragon  PG-13  Movie
41                                       Jaws     PG  Movie
42                                     Jaws 2     PG  Movie
43                                     Jaws 3     PG  Movie
44                          Jaws: The Revenge  PG-13  Movie
45                     My Heroes Were Cowboys     PG  Movie
88   Blood Brothers: Malcolm X & Muhammad Ali  PG-13  Movie
94                                  Show Dogs     PG  Movie
107                          A Champion Heart      G  Movie

In [ ]:
(
    df.query("type == 'Movie' and release_year > 2015 and rating == 'PG-13'")
    [['title', 'release_year', 'country']]
    .head(10)
)

,title,release_year,country
0,Dick Johnson Is Dead,2020,United States
9,The Starling,2021,United States
38,Birth of the Dragon,2017,"China, Canada, United States"
88,Blood Brothers: Malcolm X & Muhammad Ali,2021,NaN
112,Worth,2021,NaN
117,Final Account,2021,"United Kingdom, United States"
128,Agatha Christie's Crooked House,2017,NaN
162,Marshall,2017,"United States, China, Hong Kong"
171,Same Kind of Different as Me,2017,United States
283,Misha and the Wolves,2021,"Belgium, United Kingdom"

In [ ]:
# titles that contain 'Love'
df[df['title'].str.contains('Love', na=False)] # na means null value

# country starts with 'United'
df[df['country'].str.startswith('United', na=False)]

# case insensitive search
df[df['title'].str.contains('love', case=False, na=False)]

In [20]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
# drop rows where ANY column has null
df.dropna()

# drop rows where SPECIFIC column has null
df.dropna(subset=['rating'])

# drop rows where ALL columns are null
df.dropna(how='all')

# drop columns that have nulls
df.dropna(axis=1)

In [ ]:
# ✅ clean chaining approach
(
    df
    .dropna(subset=['director'])
    [['title', 'director', 'country']]
    .head()
)

In [ ]:
# fill with a static value
df['rating'].fillna('Not Rated')

# text columns → fill with 'Unknown' or most frequent value
df['country'].fillna('Unknown')
df['rating'].fillna(df['rating'].mode()[0])  # most frequent rating

# fill with mean/median — for numeric columns
df['release_year'].fillna(df['release_year'].mean())

# numeric columns → fill with median (more robust than mean)
df['release_year'].fillna(df['release_year'].median())

# fill with forward fill — use previous row's value
df['date_added'].fillna(method='ffill')

# fill with backward fill — use next row's value
df['date_added'].fillna(method='bfill')

In [ ]:
# rename specific columns
# 💼 Industry Practice — rename while chaining
(
    df.rename(columns={'listed_in': 'genre'
                       'date_added': 'added_date'
                       })
    [['title', 'genre', 'type']]
    .head()
)

In [ ]:
# make all columns lowercase, replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [ ]:
# drop single column
df.drop(columns=['show_id'])

# drop multiple columns
df.drop(columns=['show_id', 'description'])

# drop specific rows by index
df.drop(index=[0, 1, 2])

# 💼 Industry Practice — chain it
(
    df.drop(columns=['show_id', 'description'])
    .head()
)

In [ ]:
# check current dtypes
df.dtypes

# convert release_year from int to string
df['release_year'].astype(str)

# convert a column to category — saves memory on repetitive text
df['type'].astype('category')
df['rating'].astype('category')

In [14]:
df['country'].memory_usage()

70588

In [15]:
df['country'].astype('category').memory_usage()

40282

In [18]:
# check duplicates
df.duplicated().sum()

# check duplicates on specific column
df.duplicated(subset=['title']).sum()

# view duplicate rows
df[df.duplicated(subset=['title'])]

# drop duplicates
df.drop_duplicates()

# drop duplicates on specific column, keep last occurrence
df.drop_duplicates(subset=['title'], keep='last')

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [ ]:
# convert date_added from string to datetime
df['date_added'] = pd.to_datetime(df['date_added'])

# now you can extract parts
df['date_added'].dt.year
df['date_added'].dt.month
df['date_added'].dt.day_name()   # Monday, Tuesday...

# 💼 Industry Practice — create new columns from dates
(
    df.assign(
        year_added = df['date_added'].dt.year,
        month_added = df['date_added'].dt.month
    )
    [['title', 'date_added', 'year_added', 'month_added']]
    .head()
)

In [ ]:
# remove leading/trailing spaces
df['title'].str.strip()

# convert to lowercase
df['title'].str.lower()

# replace within string
df['duration'].str.replace(' min', '').str.replace(' Season', 'S')

# split a column — duration has '90 min' or '2 Seasons'
df['duration'].str.split(' ', expand=True)
#    0       1
# 0  90     min
# 1  2   Seasons